/* Side-effect imports: each file calls registerAreaWindow() for the windows
   it defines (see areaWindowRegistry.ts). Add a line when you add a file. */
import './CreateTaskDialog'
import './CreateMessageDialog'
import './scheduler/register'
import './WorkspaceWindows'
import './WorkspaceBlendWindows'
import './WorkspaceBasketWindows'
import './ChartBasicsWindows'
import './MyUserAccountWindow'
import './LetterWindows'
import './encounterAreaWindows'
import './CarePlanWindows'
import './PreferenceWindows'
import './CarePlanRecordWindows'
import './GoalWindows'
import './SummarySettingsView'
import './CarePlanTemplatesView'
import './ChartActionWindows'
import './ChangeTeleplanPasswordDialog'
import './PrintPreviewWindow'
import './ReportParameterWindows'
import './PatientContactDialog'
import './ScorecardWindow'
import './ReportBuilderWindow'
import './PatientsByProcedureWindow'
import './ReportSpecWindow'
import './ReportBuilderTools'
import './reports/register'
import './RecordOptionWindows'
import './AddressBookWindow'
/* admin/reference stream (E1): the Universal Search Window by name, the
   code-list lookups, and the Address Book's quick-add windows */
import './CodeLookupDialogs'
import './CodeListLookupWindows'
import './QuickEntryWindows'
import './MeasureEntryWindows'
import './DeterminantWindows'
import './billing/register'
/* letters and documents stream (C3): Attached Letters, Respond to Order and
   the Send window, Standard Mode's Referral Note, the letter template
   designer */
import './LetterResponseWindows'
import './StandardReferralWindows'
import './LetterTemplateWindows'
import './ActiveEncounterWindow'
import './PhsaEformWindows'
import './PrivateNoteWindows'
/* C3: the SRFax "Success: Fax Queued" box, opened by id (fax-queued) */
import './ViewerWindows'
