/* Side-effect imports: each file calls registerAreaWindow() for the windows
   it defines (see areaWindowRegistry.ts). Add a line when you add a file. */
import './CreateTaskDialog'
import './CreateMessageDialog'
import './scheduler/register'
import './WorkspaceWindows'
import './ChartBasicsWindows'
import './MyUserAccountWindow'
import './LetterWindows'
import './encounterAreaWindows'
import './CarePlanWindows'
import './ChartActionWindows'
import './ChangeTeleplanPasswordDialog'
import './PrintPreviewWindow'
import './ReportParameterWindows'
import './PatientContactDialog'
import './ScorecardWindow'
import './ReportBuilderWindow'
import './PatientsByProcedureWindow'
import './RecordOptionWindows'
import './AddressBookWindow'
