#!/usr/bin/env node
/* ============================================================================
   Turn a MOIS chart export into a fixture the emulator's screens can read.

   MOIS exports a chart as UTF-16 XML: one <chart> record plus repeating record
   groups for everything hanging off it. This reads the whole file and emits
   one module per chart, keyed by the MOIS chart number.

   Field names are kept EXACTLY as MOIS writes them (`str_name_l`, `dtm_dob`,
   `num_chart`). Renaming them to something friendlier would make every screen's
   mapping a guess about which export field it came from; keeping them means a
   grid column can be traced to the column MOIS filled.

   usage: node scripts/import-chart.mjs <export.xml> [outDir]
   ========================================================================= */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { basename, join } from 'node:path'

/* Record groups, in the order the emulator's tree walks them. A group absent
   from an export simply comes back empty. */
const GROUPS = [
  'chart_address', 'chart_occupant', 'chart_preference', 'chart_service', 'connection',
  'encounter', 'encounter_note', 'measure', 'panel', 'order', 'document',
  'prescription', 'drug_dose', 'drug_duration',
  'health_issue', 'allergy', 'reaction_risk', 'reaction_event',
  'adverse_event', 'adverse_agent', 'adverse_link', 'alert',
  'family_hx', 'risk', 'need', 'action', 'goal', 'goal_link',
  'mar', 'mar_action', 'mar_instruction',
  'service_event', 'service_event_diag', 'form_header', 'form_wcb',
  'dform_header', 'dform_data',
]

const src = process.argv[2]
if (!src) { console.error('usage: import-chart.mjs <export.xml> [outDir]'); process.exit(1) }
const outDir = process.argv[3] ?? join(process.cwd(), 'src/data/charts')

/* MOIS writes UTF-16 with a BOM. Reading it as utf8 yields NUL-separated
   characters that silently match nothing. */
const xml = readFileSync(src, 'utf16le').replace(/^﻿/, '')

const header = Object.fromEntries(
  [...xml.matchAll(/<(supplier|version|build|date|time|site|reference)>([^<]*)<\//g)]
    .map((m) => [m[1], m[2]]),
)

/** Leaf fields of one record, without descending into nested groups. */
function fieldsOf(block) {
  const out = {}
  /* CDATA first: MOIS wraps anything with punctuation in it */
  for (const m of block.matchAll(/<([a-z][\w_]*)><!\[CDATA\[([\s\S]*?)\]\]><\/\1>/g)) {
    out[m[1]] = m[2].trim()
  }
  for (const m of block.matchAll(/<([a-z][\w_]*)>([^<]*)<\/\1>/g)) {
    if (!(m[1] in out)) out[m[1]] = m[2].trim()
  }
  return out
}

/** Every record of one group, nested groups stripped so fields stay flat. */
function recordsOf(group) {
  const out = []
  const open = new RegExp(`<${group}>`, 'g')
  let m
  while ((m = open.exec(xml))) {
    /* find this record's matching close, allowing the same tag to nest */
    let depth = 1, i = open.lastIndex
    const tok = new RegExp(`<(/?)${group}>`, 'g')
    tok.lastIndex = i
    let t
    while (depth > 0 && (t = tok.exec(xml))) { depth += t[1] ? -1 : 1; i = t.index }
    const body = xml.slice(open.lastIndex, i)
    /* drop nested groups so a parent does not absorb its children's fields */
    let flat = body
    for (const g of GROUPS) flat = flat.replace(new RegExp(`<${g}>[\\s\\S]*?</${g}>`, 'g'), '')
    out.push(fieldsOf(flat))
    open.lastIndex = i
  }
  return out
}

const chart = fieldsOf(
  (xml.match(/<chart><id_chart>[\s\S]*?(?=<chart_address>|<chart_preference>|<encounter>)/) ?? [''])[0]
    .replace(/<(chart_address|chart_preference|chart_service|connection)>[\s\S]*?<\/\1>/g, ''),
)
const num = chart.num_chart
if (!num) { console.error('no <num_chart> in', src); process.exit(1) }

const data = { header, chart }
/* keyed by the group name MOIS uses, verbatim — pluralising turns
   `chart_address` into `chart_addresss` and buys nothing */
for (const g of GROUPS) data[g] = recordsOf(g)

mkdirSync(outDir, { recursive: true })
const name = `chart-${num}`

/* The demographics go in their own module. The roster needs them on every
   load to list the patient at all, while the records — the other 99% of the
   file — are only wanted once someone opens this chart, so they are imported
   lazily and must not be reachable from anything the roster touches. */
writeFileSync(join(outDir, `${name}.summary.ts`), `/* Generated by scripts/import-chart.mjs from ${basename(src)} — do not edit.
 * The <chart> record only: what the roster needs to list this patient.
 */
import type { MoisRecord } from './types'

export const ${name.replace(/-(\w)/g, (_, c) => c.toUpperCase())}Summary: MoisRecord = ${JSON.stringify(chart, null, 1)}
`)
const body = `/* Generated by scripts/import-chart.mjs from ${basename(src)} — do not edit.
 *
 * A real MOIS chart export, ${header.supplier} ${header.version} b${header.build},
 * site ${header.site}, reference ${header.reference}. Field names are MOIS's own.
 *
 * ${GROUPS.filter((g) => data[g].length).map((g) => `${g}: ${data[g].length}`).join(' · ')}
 */
import type { MoisChartExport } from './types'

export const ${name.replace(/-(\w)/g, (_, c) => c.toUpperCase())}: MoisChartExport = ${JSON.stringify(data, null, 1)}
`
writeFileSync(join(outDir, `${name}.ts`), body)
console.log(`${name}.ts  ${(body.length / 1024).toFixed(0)} KB`)
for (const g of GROUPS) if (data[g].length) console.log(`  ${String(data[g].length).padStart(4)}  ${g}`)
