/* Side-effect imports: every Scheduler window registers itself with the
   frame's window registry (screens/areaWindowRegistry.ts). */
import '../NewAppointmentDialog'
import './AppointmentDetail'
import './AppointmentSeriesWindows'
import './GroupBookingWindows'
import './SchedulerMenuWindows'
import './CopyMoveWindows'
import './DaybookMenus'
import './DaybookPrintWindows'
import './PreSlotWizard'
import './ProviderScheduleSummary'
import './QuickRegistration'
import './RecallWindows'
import './ReservationViews'
import './ShiftViews'
